name: Actions Setup
on:
  schedule:
    - cron: '05 19 * * *' # should match with conditions below 
    # - cron: '20 19 * * *' # should match with conditions below  
    # - cron: '35 19 * * *' # should match with conditions below 
    # - cron: '50 19 * * *' # should match with conditions below 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'develop'
        options:
        - 'develop'
        - 'staging'
        - 'production'
        - 'local'
      browser:
        type: choice
        description: 'Browser: Chrome, Firefox, Safari, all'
        required: true
        default: 'Chrome'
        options:
        - 'Chrome'
        - 'Firefox'
        - 'Safari'
        - 'all'
      test-tag:
        type: choice
        description: 'Tag of scope to test. Empty menu item - all tests (no tags)'
        required: true
        default: '-'
        options:
        - '@debug'
        - '@previous'
        - '@smoke'
        - '-'
      options:
        type: string
        description: 'Test run options (e.g.: --workers=1)'
        required: false
      skip-message:
        type: boolean
        description: 'Skip Slack message?'
        required: true
jobs:
  process:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.cron.outputs.environment }}
      skip: ${{ steps.cron.outputs.skip }}
      locally: ${{ steps.process.outputs.locally }}
      workdir: ${{ steps.process.outputs.workdir }}
      options: ${{ steps.process.outputs.options }}
    steps:
    - name: Process Cron
      id: cron
      run: |
        echo "Cron value >${{github.event.schedule}}<"
        if [[ "${{github.event.schedule}}" == "05 19 * * *" ]]
        then 
          echo "environment=production" >> "$GITHUB_OUTPUT"
        elif [[ "${{github.event.schedule}}" == "20 19 * * *" ]]
        then 
          echo "environment=production" >> "$GITHUB_OUTPUT"
        elif [[ "${{github.event.schedule}}" == "35 19 * * *" ]]
        then 
          echo "environment=staging" >> "$GITHUB_OUTPUT"
        elif [[ "${{github.event.schedule}}" == "50 19 * * *" ]]
        then 
          echo "environment=develop" >> "$GITHUB_OUTPUT"
        else
          echo "environment=${{inputs.environment}}" >> "$GITHUB_OUTPUT"
        fi
        
        echo "skip=${{inputs.skip-message}}" >> "$GITHUB_OUTPUT"
    - name: Process inputs
      id: process
      run: |
        if [[ "${{inputs.test-tag}}" == "" || "${{inputs.test-tag}}" == "-"  ]]
        then
          GREP_TAG=""
        else
          GREP_TAG="--grep ${{ inputs.test-tag }}"
        fi

        if [[ "${{inputs.browser}}" == "Chrome" ]]
        then 
          PROJECT="--project=chromium"
        elif [[ "${{inputs.browser}}" == "Firefox" ]]
        then 
          PROJECT="--project=firefox"
        elif [[ "${{inputs.browser}}" == "Safari" ]]
        then 
          PROJECT="--project=webkit"
        else
          PROJECT=""
        fi

        if [[ "${{steps.cron.outputs.environment}}" == "local" ]]
        then
          echo "locally=true" >> "$GITHUB_OUTPUT"
          echo "workdir=./" >> "$GITHUB_OUTPUT"
          echo "options=--config=e2e/playwright/playwright.config.js --project=chromium --grep @smoke" >> "$GITHUB_OUTPUT"
        else
          echo "locally=false" >> "$GITHUB_OUTPUT"
          echo "workdir=./e2e/playwright/" >> "$GITHUB_OUTPUT"
          echo "options=$GREP_TAG ${{ inputs.options }} $PROJECT" >> "$GITHUB_OUTPUT"
        fi
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: process
    steps:
    - name: Output processed inputs from the GITHUB_OUTPUT
      run: |
        echo "-------"
        echo "*** DATE: $(date) ***"
        echo "*** Environment input: ${{ inputs.environment }} ***"
        echo "*** Environment output: ${{ needs.process.outputs.environment }} ***"
        echo "*** Skip Slack output: ${{ needs.process.outputs.skip }} ***"
        echo "*** Locally output: ${{ needs.process.outputs.locally }} ***"
        echo "*** Workdir output: ${{ needs.process.outputs.workdir }} ***"
        echo "*** Options output: ${{ needs.process.outputs.options }} ***"
        echo "-------"
    # - uses: actions/checkout@v3
    # - uses: actions/setup-node@v3
    #   with:
    #    node-version: 18
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test ${{ steps.process_inputs.outputs.test-browser }} ${{ inputs.options }}
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 1
