name: Playwright Tests 2
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'staging'
        options:
        - 'develop'
        - 'staging'
        - 'production'
      browser:
        type: choice
        description: 'Browser: Chromium(the most stable), Firefox, WebKit(Safari)'
        required: true
        default: '--project=chromium'
        options:
          - '--project=chromium'
          - '--project=firefox'
          - '--project=webkit'
          - '--'
      options:
        type: string
        description: 'Test run options (e.g.: --workers=1)'
        required: false
      debug-mode:
        type: boolean
        description: 'Run all tests in one flow (makes sense for debugging purposes only)'
        required: true
      skip-message:
        type: boolean
        description: 'Skip Slack message?'
        required: true
jobs:
  test0:
    if: ${{ inputs.debug-mode }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test ${{ inputs.options }} ${{ inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  test1:
    if: ${{ !inputs.debug-mode }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: TEST 1 RUN
      run: npm ci
  test2:
    if: ${{ !inputs.debug-mode }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: TEST 2 RUN
      run: npm ci
