name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to run in'
        required: true
        default: 'staging'
        options:
        - 'develop'
        - 'staging'
        - 'production'
      browser:
        type: choice
        description: 'Browser'
        required: true
        default: 'chromium'
        options:
          - 'Chromium'
          - 'Firefox'
          - 'Webkit'
          - 'All browsers'
      options:
        type: string
        description: 'Test run options (e.g.: --workers=1)'
        required: false
      skip-message:
        type: boolean
        description: 'Skip Slack message?'
        required: true
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  run-playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      CI: true
    steps:
    - name: Process inputs and add them to the GITHUB_OUTPUT
      id: process_inputs
      run: |
        echo "Selected browser >${{inputs.browser}}<"
        if [[ "${{inputs.browser}}" == "Chromium" ]]
        then
          TEST_BROWSER='--project=chromium'
        elif [[ "${{inputs.browser}}" == "Firefox" ]]
        then
          TEST_BROWSER='--project=firefox'
        elif [[ "${{inputs.browser}}" == "Webkit" ]]
        then
          TEST_BROWSER='--project=webkit'
        else
          TEST_BROWSER=''
        fi
        echo "test-browser=$TEST_BROWSER" >> $GITHUB_OUTPUT
    - name: Output processed inputs from the GITHUB_OUTPUT
      run: |
        echo "-------"
        echo "***${{ steps.process_inputs.outputs.test-browser }}***"
        echo "-------"
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test ${{ steps.process_inputs.outputs.test-browser }} ${{ inputs.options }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: playwright-report/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
